[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/tmp/supervisord.pid

[program:bioscopeai-classifier-service]
command=/var/www/bioscopeai-classifier-service/app/bioscopeai_classifier_service_env/bin/python -m bioscopeai_classifier_service.main
directory=/var/www/bioscopeai-classifier-service/app/bioscopeai-classifier-service/
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
environment=PYTHONUNBUFFERED="1"
